In [1]:
import pandas as pd

In [2]:
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(titanic_dataset_github_url)

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [39]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [5]:
df['Name'].str.replace("Mr.", "Sir", regex=False).head() #regex use for matching patterns format string etc etc

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [6]:
df['Name'].head() # here original change nhi hua kyoki we dont copied upar wala in new object

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [7]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [8]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [11]:
start = df.loc[1, 'Name'].find("(")
start

27

In [12]:
end = df.loc[1, 'Name'].find(")")
end

50

In [ ]:
#let in above dataframe we want to remove substring in 1st row that is (Florence Briggs Thayer) and baki ko nhi remove karna
#1st method
df.loc[1, 'Name'][0:start] + df.loc[1, 'Name'][end+1:]

'Cumings, Mrs. John Bradley '

In [14]:
def remove_substring(name): #using python without pandas
    start = name.find("(")
    end = name.find(")")
    new_name = name[0:start] + name[end+1:]
    new_name = new_name.strip()
    return new_name

In [15]:
df["Name_trimmed"] = df["Name"].apply(remove_substring)

In [16]:
df["Name_trimmed"].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_trimmed, dtype: str

In [17]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [18]:
df.loc[1, 'Name_trimmed']

'Cumings, Mrs. John Bradley'

In [19]:
# Replace Substrings with Regex : regular expression , NOTE : REGEX IS NOT IMPORTANT TO LEARN AND IT IS TOUGH UPAR UPAR SE SAMJHO AND USE AI THAT LIKE SIR USED NICHE BUT THODA BAHUT YOU SHOULD KNOW HOW IT MADE AND WHAT IT DO AND HOW

# * means zero or more
# . match any character
# "\(.*\)" means \( means ( escape kiya then .* zero or more character escape kiya then \) means iske bad ka ) escape kiya

# windows : USE THID \\ OR r"" wala in down kiya hua hai(preferable for all)
df['Name'].str.replace(r"\(.*\)", "", regex=True).head()

0          Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henry
Name: Name, dtype: str

| Part | Meaning                                                              |
| ---- | -------------------------------------------------------------------- |
| `r`  | Raw string literal — tells Python **not to interpret** `\` as escape |
| `\(` | Escaped `(` — matches a literal opening parenthesis                  |
| `.*` | Dot `.` matches **any character**, and `*` means **zero or more**    |
| `\)` | Escaped `)` — matches a literal closing parenthesis                  |

In [ ]:
# Let to check which email is valid , invalid with regex karke dekhte hai
# hello@ghail@abc.com

# python logic

# regex pattern

In [20]:
import re #use like this as a developer

In [21]:
def is_valid_email(email):
    # Regex Breakdown:
    # ^[a-zA-Z0-9._%+-]+ : Alphanumeric + common symbols in username
    # @                  : Mandatory @ symbol
    # [a-zA-Z0-9.-]+     : Alphanumeric, dots, or hyphens in domain
    # \.[a-zA-Z]{2,}$    : Must end with a dot followed by 2 or more letters
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'   #we copied this pattern from internet and  used because yad nhi rakh skte

    # re.fullmatch returns a Match object if valid, otherwise None
    if re.fullmatch(pattern, email):
        return True
    return False

# Test cases
emails = ["user@example.com", "invalid-email", "name.surname@sub.domain.org", "hello@ghail@abc.com"]
for e in emails:
    print(f"{e}: {'Valid' if is_valid_email(e) else 'Invalid'}")

user@example.com: Valid
invalid-email: Invalid
name.surname@sub.domain.org: Valid
hello@ghail@abc.com: Invalid

# Split and Access Elements

In [22]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [23]:
df['Name'].str.split(",")[0] #separated with ,

['Braund', ' Mr. Owen Harris']

In [25]:
df['Name'].str.split()[0] #by default split take space to separate

['Braund,', 'Mr.', 'Owen', 'Harris']

In [ ]:
df['Name'].str.split().str[0] #only zeroth index in every string

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

In [ ]:
print(df['Name'].str.split()[0][0]) #let for zeroth row wala dekhna

Braund,

# Strip Spaces

In [28]:
df['Name'].str.strip() #removing right and left spaces

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [29]:
df['Name'].str.lstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [30]:
df['Name'].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

# Find Position of Substring

In [ ]:
df['Name'].str.find("Mr") # finding index and -1 means Mr not present in that string

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [40]:
df['Name'].str.contains("Miss")

0      False
1      False
2       True
3      False
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [41]:
# "Miss"
# Count passengers with “Miss” in name

count = df['Name'].str.contains("Miss").sum()
print("Number of 'Miss':", count)

Number of 'Miss': 182

In [42]:
data = {
    'Name': [
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email': [
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

df = pd.DataFrame(data)

In [43]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [ ]:
df['Name'].str.pad(width=20, side='left', fillchar='-') #done in numpy also

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

# Categorical Data in Pandas
### VERYIMP in ML
### 📌 What is Categorical Data?  

Categorical data is textual or labeled data that represents discrete categories.

In [44]:
class_data = {
    "Name" : ["A", "B", "C", "D"],
    "Groups" : ["G1", "G2", "G3", "G4"]
}

In [45]:
class_df = pd.DataFrame(class_data)

In [46]:
class_df

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [58]:
# df['Groups'] > "G4"

In [ ]:
# G3, G1, G2, G4 --> Higher to lower order bnana hai
# df['Groups'] > "G4"
# G1 > G4 --> True

In [ ]:
class_df.info() # see groups ka dtype is str so if g1>g4 karenge after giving order also then it will give error because str > str toh nhi ho skta like see ( we can say 2>1 but we cant say in coding "two" > "one " ) because it is string
#SO WE WILL MAKE CATEGORIES

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [ ]:
class_df['Group_cat']= pd.Categorical( #NOW EK COL BNAYA Group_cat ka and usme ye Categorical chalaya
    class_df['Groups'],
    categories=['G3', 'G1', 'G2', 'G4'], # Custom order lower to higher(ascending) #G3 is smallest and G4 is largest according to this
    # 'G3' : 1, 'G1' : 2, 'G2' : 3, 'G4' : 4
    ordered=True #means ki jo order diya wo true hai usi ke hisab se karo
)

In [ ]:
print(class_df)
class_df.info() #Now see Group_cat me dtype category aa gya

  Name Groups Group_cat
0    A     G1        G1
1    B     G2        G2
2    C     G3        G3
3    D     G4        G4
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Groups     4 non-null      str
 2   Group_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [ ]:
class_df['Group_cat'].cat.categories #our category order #for string we use str and for category we use .cat and their methods

Index(['G3', 'G1', 'G2', 'G4'], dtype='str')

In [ ]:
class_df['Group_cat'] >= "G4" #valid easy

0    False
1    False
2    False
3     True
Name: Group_cat, dtype: bool

In [54]:
class_df

  Name Groups Group_cat
0    A     G1        G1
1    B     G2        G2
2    C     G3        G3
3    D     G4        G4

In [56]:
df = pd.read_csv(titanic_dataset_github_url)

In [57]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:
#ye titanic wali repositry me se liya see info me 11 no wala for performing some operation ye koi concept nhi hai
df['Embarked'].unique() # the port where a passenger boarded the ship, indicated by a single-letter code
# C (Cherbourg)
# Q (Queenstown)
# S (Southampton)

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [63]:
df['Embarked'] = df['Embarked'].fillna("N") #nan ko "N" kar diya

In [64]:
df['Embarked'].unique()
#  Let C (Cherbourg) --> 1000000
# Q (Queenstown) --> 5000000
# S (Southampton) ---> 100000
# N --> Not provided ---> 000000

# Let we want order of N S C Q


# Find all the passenger >  100000 > S

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [65]:
df['Embarked_auto_cat'] = df['Embarked'].astype('category')

In [66]:
df['Embarked_auto_cat'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [67]:
df['Embarked_cust_cat']= pd.Categorical(
    df['Embarked'],
    categories=['N', 'S', 'C', 'Q'], # Custom order lower to higher (Ascending)
    ordered=True
)

In [68]:
df['Embarked_cust_cat'].cat.categories #

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [69]:
df['Embarked_cust_cat'] > 'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [70]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [71]:
df['Embarked_cust_cat'].cat.codes.head()

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [72]:
# df['Sex']

# i want you to convert the values of Sex column and encode them in 0 & 1

df['Sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [ ]:
#all three working
# df['Sex_cat_custom'] = df['Sex'].astype('category').cat.codes

# df['Sex_cat_custom'] = df['Sex'].replace(['female', 'male'], [0, 1])

# df['Sex_cat_custom'] = df['Sex'].apply(lambda sex: 1 if sex == 'male' else 0)

# Date Functionality in Pandas

In [74]:
df = pd.DataFrame({
    'event': ['Concert', 'Conference', 'Wedding'],
    'date': ['2025-01-01', '2025-03-15', '2025-07-20'] #Normally , it will take date in string
})

In [ ]:
df.info() #see date in str

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [76]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [ ]:

df['date_pandas'] = pd.to_datetime(df['date']) #to_datetime se ye dtype datetime ho jega which provided by pandas #Here hamne new column bnaya hai for datetime
# format: optional format (e.g. '%d/%m/%Y')

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [80]:
df.head()

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [81]:
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
Name: date_pandas, dtype: int32

In [82]:
df['date_pandas'].dt.month

0    1
1    3
2    7
Name: date_pandas, dtype: int32

In [83]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [85]:
df['date_pandas'].dt.weekday #0 means Monday then so on

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [86]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [87]:
df[df['date_pandas'] > '2025-04-01']

     event        date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [88]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

# Creating Datetime Ranges

Other frequencies:

'M' → month end

'MS' → month start

'W' → weekly

'H', 'T', 'S' → hour, minute, second

In [ ]:
pd.date_range(start='2026-02-01', end='2026-02-10', freq='D') #D means all dates

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[us]', freq='D')

In [90]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='ME')

DatetimeIndex(['2024-01-31', '2024-02-29'], dtype='datetime64[us]', freq='ME')

In [91]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='MS')

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[us]', freq='MS')

# Date Arithmetic

In [ ]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days=7) #to add singlular data we use Timedelta to add next 7 days means add ho gya

In [95]:
pd.Timedelta(days=7)

Timedelta('7 days 00:00:00')

In [96]:
pd.Timestamp.today()

Timestamp('2026-05-09 06:16:20.989597')

In [94]:
df.head()

        event        date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [97]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [98]:
df.head()

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -494 days +17:42:41.772993
1  Conference  2025-03-15  2025-03-15 2025-03-22 -421 days +17:42:41.772993
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -294 days +17:42:41.772993

# PANDAS COMPLETED

==================================================